# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filetransfer.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66iletransfer.proto\x12\x0c\x66iletransfer\"E\n\x13simpleUploadRequest\x12\x1c\n\x14\x63lientCalculatedHash\x18\x01 \x01(\t\x12\x10\n\x08\x66ileData\x18\x02 \x01(\x0c\"7\n\x11simpleUploadReply\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t2o\n\x17SimpleFileUploadService\x12T\n\x0csimpleUpload\x12!.filetransfer.simpleUploadRequest\x1a\x1f.filetransfer.simpleUploadReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'filetransfer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIMPLEUPLOADREQUEST']._serialized_start=36
  _globals['_SIMPLEUPLOADREQUEST']._serialized_end=105
  _globals['_SIMPLEUPLOADREPLY']._serialized_start=107
  _globals['_SIMPLEUPLOADREPLY']._serialized_end=162
  _globals['_SIMPLEFILEUPLOADSERVICE']._serialized_start=164
  _globals['_SIMPLEFILEUPLOADSERVICE']._serialized_end=275
# @@protoc_insertion_point(module_scope)
